"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useState, useSyncExternalStore } from "react";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { emptyCart, readCart, subscribeToCart, writeCart } from "@/lib/cart";
import { auth } from "@/lib/firebase";

const formSchema = z.object({ fullName: z.string().trim().min(2, "Enter your full name"), phone: z.string().trim().min(7, "Enter a valid phone number"), email: z.union([z.literal(""), z.string().email("Enter a valid email")]), county: z.string().trim().min(2, "Required"), town: z.string().trim().min(2, "Required"), area: z.string().trim().min(2, "Required"), street: z.string().trim().min(2, "Required"), directions: z.string().max(500).optional(), fulfilment: z.enum(["DELIVERY", "PICKUP"]), paymentMethod: z.enum(["PAY_ON_PICKUP", "CASH", "MPESA"]) });
type FormValues = z.infer<typeof formSchema>;
const money = (value: number) => `KES ${value.toLocaleString("en-KE")}`;

export function CheckoutPage() {
  const router = useRouter(); const lines = useSyncExternalStore(subscribeToCart, readCart, emptyCart); const [serverError, setServerError] = useState("");
  const { register, handleSubmit, formState: { errors, isSubmitting } } = useForm<FormValues>({ resolver: zodResolver(formSchema), defaultValues: { fulfilment: "PICKUP", paymentMethod: "PAY_ON_PICKUP" } });
  const total = useMemo(() => lines.reduce((sum, line) => sum + line.unitPrice * line.quantity, 0), [lines]);
  const submit = async (values: FormValues) => { setServerError(""); if (!lines.length) return setServerError("Your basket is empty."); const token = await auth.currentUser?.getIdToken(); const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify({ lines: lines.map(({ productId, quantity }) => ({ productId, quantity })), customer: { fullName: values.fullName, phone: values.phone, email: values.email }, address: { county: values.county, town: values.town, area: values.area, street: values.street, directions: values.directions }, fulfilment: values.fulfilment, paymentMethod: values.paymentMethod }) }); const result = await response.json(); if (!response.ok) return setServerError(result.error ?? "We could not place your order."); writeCart([]); router.push(`/order-success?order=${encodeURIComponent(result.orderNumber)}`); };
  return <main className="checkout-page"><header><Link href="/cart">← Back to basket</Link><b>Vitour Xpress secure checkout</b></header><div className="checkout-layout"><form onSubmit={handleSubmit(submit)}><p className="eyebrow">COMPLETE YOUR ORDER</p><h1>Checkout</h1><fieldset><legend>Customer details</legend><label>Full name<input {...register("fullName")} />{errors.fullName && <span>{errors.fullName.message}</span>}</label><label>Phone number<input inputMode="tel" {...register("phone")} />{errors.phone && <span>{errors.phone.message}</span>}</label><label>Email <small>(optional)</small><input type="email" {...register("email")} />{errors.email && <span>{errors.email.message}</span>}</label></fieldset><fieldset><legend>Delivery address</legend><div className="form-pair"><label>County<input {...register("county")} />{errors.county && <span>{errors.county.message}</span>}</label><label>Town / city<input {...register("town")} />{errors.town && <span>{errors.town.message}</span>}</label></div><div className="form-pair"><label>Area<input {...register("area")} />{errors.area && <span>{errors.area.message}</span>}</label><label>Street / building<input {...register("street")} />{errors.street && <span>{errors.street.message}</span>}</label></div><label>Directions <small>(optional)</small><textarea {...register("directions")} /></label></fieldset><fieldset><legend>Fulfilment</legend><label className="radio"><input type="radio" value="PICKUP" {...register("fulfilment")} /> Shop pickup</label><label className="radio"><input type="radio" value="DELIVERY" {...register("fulfilment")} /> Delivery</label></fieldset><fieldset><legend>Payment method</legend><label className="radio"><input type="radio" value="PAY_ON_PICKUP" {...register("paymentMethod")} /> Pay on pickup</label><label className="radio"><input type="radio" value="CASH" {...register("paymentMethod")} /> Cash / manual</label><label className="radio"><input type="radio" value="MPESA" {...register("paymentMethod")} /> M-Pesa manual confirmation</label></fieldset>{serverError && <p className="form-error">{serverError}</p>}<button className="button button-red" disabled={isSubmitting}>{isSubmitting ? "Placing order…" : "Place secure order →"}</button></form><aside className="checkout-summary"><h2>Order summary</h2>{lines.map((line) => <div key={line.productId}><span>{line.quantity}× {line.name}</span><b>{money(line.quantity * line.unitPrice)}</b></div>)}<hr /><div className="summary-total"><span>Total</span><b>{money(total)}</b></div></aside></div></main>;
}
