"use client";

import { collection, onSnapshot, orderBy, query } from "firebase/firestore";
import { ChangeEvent, FormEvent, useEffect, useState } from "react";
import { db } from "@/lib/firebase";
import type { Product } from "@/lib/domain";
import { useStaffToken } from "./staff-gate";

const money = (value: number) => `KES ${value.toLocaleString("en-KE")}`;
export function InventoryClient() {
  const token = useStaffToken(); const [products, setProducts] = useState<Product[]>([]); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [images, setImages] = useState<string[]>([]);
  useEffect(() => onSnapshot(query(collection(db, "products"), orderBy("name")), (snapshot) => setProducts(snapshot.docs.map((item) => ({ id: item.id, ...item.data() }) as Product)), () => setError("Unable to load inventory.")), []);
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !token) return; setError(""); const signature = await fetch("/api/cloudinary/signature", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ kind: "product" }) }); const signed = await signature.json(); if (!signature.ok) return setError(signed.error ?? "Image upload is unavailable."); const data = new FormData(); data.set("file", file); data.set("api_key", signed.apiKey); data.set("timestamp", String(signed.timestamp)); data.set("folder", signed.folder); data.set("signature", signed.signature); const uploaded = await fetch(`https://api.cloudinary.com/v1_1/${signed.cloudName}/image/upload`, { method: "POST", body: data }); const result = await uploaded.json(); if (!uploaded.ok) return setError(result.error?.message ?? "Image upload failed."); setImages((current) => [...current, result.secure_url]); };
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!token) return; setSaving(true); setError(""); const data = new FormData(event.currentTarget); const number = (key: string) => Number(data.get(key) || 0); const response = await fetch("/api/manage/products", { method: "POST", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), sku: data.get("sku"), brand: data.get("brand"), category: data.get("category"), tyreSize: data.get("tyreSize") || undefined, tyreType: data.get("tyreType") || undefined, vehicleType: data.get("vehicleType") || undefined, costPrice: number("costPrice"), sellingPrice: number("sellingPrice"), onlinePrice: data.get("onlinePrice") ? number("onlinePrice") : undefined, reorderLevel: number("reorderLevel"), initialStock: number("initialStock"), imageUrls: images, featured: data.get("featured") === "on" }) }); const result = await response.json(); setSaving(false); if (!response.ok) return setError(result.error ?? "Could not save product."); event.currentTarget.reset(); setImages([]); };
  return <div className="inventory-view"><section className="manager-panel"><div><p className="eyebrow">CATALOGUE CONTROL</p><h2>Add stock product</h2><p>Adding opening stock creates a permanent inventory movement. Uploaded images replace image placeholders immediately.</p></div><form onSubmit={submit} className="inventory-form"><label>Product name<input name="name" required /></label><label>SKU<input name="sku" required /></label><label>Brand<input name="brand" required /></label><label>Category<select name="category" defaultValue="TYRE"><option>TYRE</option><option>RIM</option><option>TUBE</option><option>VALVE</option><option>ACCESSORY</option><option>LUBRICANT</option><option>PART</option></select></label><label>Tyre size <small>(optional)</small><input name="tyreSize" placeholder="205/55 R16" /></label><label>Type / vehicle <input name="tyreType" placeholder="SUV, all-season…" /></label><label>Cost price<input name="costPrice" type="number" min="0" required /></label><label>Selling price<input name="sellingPrice" type="number" min="1" required /></label><label>Online price <small>(optional)</small><input name="onlinePrice" type="number" min="1" /></label><label>Opening stock<input name="initialStock" type="number" min="0" required /></label><label>Reorder level<input name="reorderLevel" type="number" min="0" required /></label><label className="image-upload">Product images<input type="file" accept="image/*" onChange={upload} />{images.length ? <span>{images.length} image(s) uploaded</span> : <span>Upload image (optional)</span>}</label><label className="check-label"><input type="checkbox" name="featured" /> Feature on website</label>{error && <p className="form-error">{error}</p>}<button className="button button-red" disabled={saving}>{saving ? "Saving…" : "Save product"}</button></form></section><section className="inventory-table"><div className="table-heading"><h2>Live inventory</h2><span>{products.length} product(s)</span></div>{error && !products.length && <p className="form-error">{error}</p>}<div className="table-scroll"><table><thead><tr><th>Product</th><th>SKU</th><th>Cost</th><th>Selling</th><th>Stock</th><th>Value</th><th>Status</th></tr></thead><tbody>{products.map((product) => <tr key={product.id}><td><b>{product.name}</b><small>{product.brand}{product.tyreSize ? ` · ${product.tyreSize}` : ""}</small></td><td>{product.sku}</td><td>{money(product.costPrice)}</td><td>{money(product.sellingPrice)}</td><td>{product.quantityInStock}</td><td>{money(product.quantityInStock * product.costPrice)}</td><td><span className={product.quantityInStock <= 0 ? "status out" : product.quantityInStock <= product.reorderLevel ? "status low" : "status in"}>{product.quantityInStock <= 0 ? "Out" : product.quantityInStock <= product.reorderLevel ? "Low" : "In stock"}</span></td></tr>)}</tbody></table></div></section></div>;
}
